### ISSUE TITLE
Tanya lisensi

### ISSUE THREAD

**Issue by emsuryadi** [baik-lang/micro-baik-lang#9]
Mengutip dari [LICENSE](https://github.com/baik-lang/micro-baik-lang/blob/master/LICENSE) pada poin nomor 0.
`Desain Program dan Kode Sumber BAIK versi 8 memiliki hak cipta dan bersifat rahasia`
sebenarnya BAIK itu open source atau closed source?

**Comment by anak10thn** [comment]
baik bersifat open source yg saat ini bisa kalian nikmati

**Comment by handrawanw** [comment]
Bang BAIK di android sudah support grafis kah ?
